<Project>
  <PropertyGroup>
    <JammerVersionFile>$(MSBuildThisFileDirectory)VERSION</JammerVersionFile>
    <JammerVersion Condition="'$(JammerVersion)' == ''">$([System.IO.File]::ReadAllText('$(JammerVersionFile)').Trim())</JammerVersion>
    <Version>$(JammerVersion)</Version>
    <InformationalVersion>$(JammerVersion)</InformationalVersion>
  </PropertyGroup>


  <PropertyGroup>
      <PublishReadyToRun>true</PublishReadyToRun>
      <PublishTrimmed>false</PublishTrimmed>
      <OptimizationPreference>Speed</OptimizationPreference>
      <ServerGarbageCollection>true</ServerGarbageCollection> 
      <RetainVMGarbageCollection>true</RetainVMGarbageCollection>
      <PublishAot>false</PublishAot>
  </PropertyGroup>
</Project>
