<Project>
  <PropertyGroup>
    <JammerVersionFile>$(MSBuildThisFileDirectory)VERSION</JammerVersionFile>
    <JammerVersion Condition="'$(JammerVersion)' == ''">$([System.IO.File]::ReadAllText('$(JammerVersionFile)').Trim())</JammerVersion>
    <Version>$(JammerVersion)</Version>
    <InformationalVersion>$(JammerVersion)</InformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <OptimizationPreference>Speed</OptimizationPreference>
    
    <!-- Aggressive binary size and performance optimizations -->
    <DebuggerSupport>false</DebuggerSupport>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <EventSourceSupport>false</EventSourceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>
</Project>
