#!/bin/bash
export LD_LIBRARY_PATH=$APPDIR/usr/lib
if [ ! -d "$HOME/jammer" ]; then
  mkdir -p $HOME/jammer/locales
  cp $APPDIR/usr/locales/* $HOME/jammer/locales 2>&1 >/dev/null
fi
exec $APPDIR/usr/bin/jammer $@
