name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-mac:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies (FUSE for AppImage tool)
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2

    - name: Build Linux x64 (Intel AppImage)
      run: python3 scripts/build.py -t linux-x64

    - name: Build Linux arm64
      run: python3 scripts/build.py -t linux-arm64

    - name: Build macOS x64
      run: python3 scripts/build.py -t osx-x64

    - name: Build macOS arm64
      run: python3 scripts/build.py -t osx-arm64

    - name: Upload Linux x64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: artifacts/jammer-*-x86_64.*
        if-no-files-found: error

    - name: Upload Linux arm64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-arm64
        path: artifacts/jammer-*-arm64.*
        if-no-files-found: error

    - name: Upload macOS x64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-x64
        path: artifacts/jammer-*-osx-x64.*
        if-no-files-found: error

    - name: Upload macOS arm64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64
        path: artifacts/jammer-*-osx-arm64.*
        if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build Windows x64 (NSIS)
      run: python scripts/build.py -t win-x64 --nsis

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-x64
        path: artifacts/Jammer-Setup_V*.exe
        if-no-files-found: error
